site_name: SRD 5.1
site_url: https://palikhov.github.com/5ethsrd-mkdocs/
repo_url: https://palikhov.github.com/5ethsrd-mkdocs/
copyright: Rules provided by Wizards of the Coast under the <a href="/license/">OGL 1.0a</a>.
site_description: Веб версия справочного документа 5.1
theme:
  name: null
  color: "rgb(216, 25, 33)" # Match with @brand-primary in variables.less
  custom_dir: purecss_theme
plugins:
  - mkdocs-simple-hooks:
      hooks:
        on_post_page: "plugins.table-styler:style_tables"
        on_pre_build: "plugins.css_minifier:generate_inline_css"
  - section-index
extra:
  enable_snigel_ads: yes
  enable_ga: no

